#!/bin/sh
#TEST {
echo "## Current user: `id`"; \
echo "## Runtime Environment variables {"; \
set; \
echo "## }"
echo "## HTTPD config summary {"; \
HTTPD_MAIN_CONF="${HTTPD_CONF_DIR}/httpd.conf"
cat "${HTTPD_MAIN_CONF}" |grep "Listen"
cat "${HTTPD_MAIN_CONF}" |grep "ServerName"
cat "${HTTPD_MAIN_CONF}" |grep "ServerRoot"
cat "${HTTPD_MAIN_CONF}" |grep "DocumentRoot"
cat "${HTTPD_MAIN_CONF}" |grep "User"
cat "${HTTPD_MAIN_CONF}" |grep "Group"
cat "${HTTPD_MAIN_CONF}" |grep "Proxy"
cat "${HTTPD_MAIN_CONF}" |grep "CustomLog"
cat "${HTTPD_MAIN_CONF}" |grep "ErrorLog"
cat "${HTTPD_MAIN_CONF}" |grep "Include"
echo "## }"
# }

set -x

#Start PHP-FPM
exec php-fpm &

# Apache gets grumpy about PID files pre-existing
rm -f ${HTTPD_PID_DIR}/httpd.pid

exec httpd -DFOREGROUND
