#!/bin/bash
#TEST {

echo "## Current user: `id`"
echo "## Runtime Environment variables {"
set
echo "## }"

echo "## HTTPD config summary {"
HTTPD_MAIN_CONF="${HTTPD_CONF_DIR}/httpd.conf"
echo "[${HTTPD_MAIN_CONF}]"
cat "${HTTPD_MAIN_CONF}" |grep -iE '^(\s*Listen)\s+'
cat "${HTTPD_MAIN_CONF}" |grep -iE  '^(\s*ServerName)\s+'
cat "${HTTPD_MAIN_CONF}" |grep -iE  '^(\s*ServerRoot)\s+'
cat "${HTTPD_MAIN_CONF}" |grep -iE  '^(\s*DocumentRoot)\s+'
cat "${HTTPD_MAIN_CONF}" |grep -iE  '^(\s*User)\s+'
cat "${HTTPD_MAIN_CONF}" |grep -iE  '^(\s*Group)\s+'
cat "${HTTPD_MAIN_CONF}" |grep -iE  '^(\s*Proxy)\s+'
cat "${HTTPD_MAIN_CONF}" |grep -iE  '^(\s*CustomLog)\s+'
cat "${HTTPD_MAIN_CONF}" |grep -iE  '^(\s*ErrorLog)\s+'
cat "${HTTPD_MAIN_CONF}" |grep -iE  '^(\s*LoadModule)\s+'
cat "${HTTPD_MAIN_CONF}" |grep -iE  '^(\s*Include)\s+'
echo "## }"


echo "## PHP config summary {"
PHP_INI_CONF="${PHP_CONF_DIR}/php.ini"
echo "[${PHP_INI_CONF}]"
    cat "${PHP_INI_CONF}" |grep -iE '^(\s*display_errors)\s*\='
    cat "${PHP_INI_CONF}" |grep -iE '^(\s*error_reporting)\s*\='
    cat "${PHP_INI_CONF}" |grep -iE '^(\s*log_error)\s*\='
    cat "${PHP_INI_CONF}" |grep -iE '^(\s*error_log)\s*\='
    cat "${PHP_INI_CONF}" |grep -iE '^(\s*extension)\s*\='

PHPFPM_MAIN_CONF="${PHP_CONF_DIR}/php-fpm.conf"
echo "[${PHPFPM_MAIN_CONF}]"
    cat "${PHPFPM_MAIN_CONF}" |grep -iE '^(\s*error_log)\s*\='
    cat "${PHPFPM_MAIN_CONF}" |grep -iE '^(\s*user)\s*\='
    cat "${PHPFPM_MAIN_CONF}" |grep -iE '^(\s*group)\s*\='

PHPFPM_WWW_CONF="${PHP_CONF_DIR}/php-fpm.d/www.conf"
echo "[${PHPFPM_WWW_CONF}]"
    cat "${PHPFPM_WWW_CONF}" |grep -iE '^(\s*access\.log)\s*\='
    cat "${PHPFPM_WWW_CONF}" |grep -iE '^(\s*slowlog)\s*\='

echo "## }"

# }

set -ex

#Verify HTTPD config
httpd -t

#Start PHP-FPM
exec php-fpm &

# Apache gets grumpy about PID files pre-existing
rm -f ${HTTPD_PID_DIR}/httpd.pid || true

exec httpd -DFOREGROUND
