#!/bin/sh
#TEST {
echo "## Current user: `id`"; \
echo "## Runtime Environment variables {"; \
set; \
echo "## }"
echo "## HTTPD config summary {"; \
cat "${HTTPD_CONF_DIR}/httpd.conf" |grep "Listen"
cat "${HTTPD_CONF_DIR}/httpd.conf" |grep "ServerName"
cat "${HTTPD_CONF_DIR}/httpd.conf" |grep "ServerRoot"
cat "${HTTPD_CONF_DIR}/httpd.conf" |grep "DocumentRoot"
cat "${HTTPD_CONF_DIR}/httpd.conf" |grep "Proxy"
cat "${HTTPD_CONF_DIR}/httpd.conf" |grep "Include"
echo "## }"
# }

set -x

#Start PHP-FPM
exec php-fpm &

# Apache gets grumpy about PID files pre-existing
rm -f ${HTTPD_PID_DIR}/httpd.pid

exec httpd -DFOREGROUND
